# Generated by papers/wording/generate.sh -- do not edit.
# The paper's wording fragments, in document order.
WORDING_MD := \
	wording/transcode.syn.md \
	wording/transcode.errors.md \
	wording/transcode.reqs.md \
	wording/transcode.codec.md \
	wording/null.term.syn.md \
	wording/null.term.sentinel.md \
	wording/null.term.view.md \
	wording/null.term.adaptor.md
