# Generated by papers/wording/generate.sh -- do not edit.
# The paper's wording fragments, in document order.
WORDING_MD := \
	wording/null.term.syn.md \
	wording/null.term.sentinel.md \
	wording/null.term.view.md
