// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
// This file is generated by tools/generate_labels.py — do not edit directly.

#ifndef INCLUDE_BEMAN_TRANSCODE_DETAIL_LABELS_HPP
#define INCLUDE_BEMAN_TRANSCODE_DETAIL_LABELS_HPP

#include <beman/transcode/config.hpp>

#include <beman/transcode/whatwg_decode_view.hpp>

#if !BEMAN_TRANSCODE_USE_MODULES()
#include <algorithm>
#include <optional>
#include <string_view>

#endif
namespace beman::transcoding {

namespace detail {

struct label_entry {
    const char* label;
    codec       value;
};

inline constexpr label_entry label_table[] = {
    {"866", codec::ibm866},
    {"ansi_x3.4-1968", codec::windows_1252},
    {"arabic", codec::iso_8859_6},
    {"ascii", codec::windows_1252},
    {"asmo-708", codec::iso_8859_6},
    {"big5", codec::big5},
    {"big5-hkscs", codec::big5},
    {"chinese", codec::gbk},
    {"cn-big5", codec::big5},
    {"cp1250", codec::windows_1250},
    {"cp1251", codec::windows_1251},
    {"cp1252", codec::windows_1252},
    {"cp1253", codec::windows_1253},
    {"cp1254", codec::windows_1254},
    {"cp1255", codec::windows_1255},
    {"cp1256", codec::windows_1256},
    {"cp1257", codec::windows_1257},
    {"cp1258", codec::windows_1258},
    {"cp819", codec::windows_1252},
    {"cp866", codec::ibm866},
    {"csbig5", codec::big5},
    {"cseuckr", codec::euc_kr},
    {"cseucpkdfmtjapanese", codec::euc_jp},
    {"csgb2312", codec::gbk},
    {"csibm866", codec::ibm866},
    {"csiso2022jp", codec::iso_2022_jp},
    {"csiso2022kr", codec::replacement},
    {"csiso58gb231280", codec::gbk},
    {"csiso88596e", codec::iso_8859_6},
    {"csiso88596i", codec::iso_8859_6},
    {"csiso88598e", codec::iso_8859_8},
    {"csiso88598i", codec::iso_8859_8_i},
    {"csisolatin1", codec::windows_1252},
    {"csisolatin2", codec::iso_8859_2},
    {"csisolatin3", codec::iso_8859_3},
    {"csisolatin4", codec::iso_8859_4},
    {"csisolatin5", codec::windows_1254},
    {"csisolatin6", codec::iso_8859_10},
    {"csisolatin9", codec::iso_8859_15},
    {"csisolatinarabic", codec::iso_8859_6},
    {"csisolatincyrillic", codec::iso_8859_5},
    {"csisolatingreek", codec::iso_8859_7},
    {"csisolatinhebrew", codec::iso_8859_8},
    {"cskoi8r", codec::koi8_r},
    {"csksc56011987", codec::euc_kr},
    {"csmacintosh", codec::macintosh},
    {"csshiftjis", codec::shift_jis},
    {"csunicode", codec::utf_16le},
    {"cyrillic", codec::iso_8859_5},
    {"dos-874", codec::windows_874},
    {"ecma-114", codec::iso_8859_6},
    {"ecma-118", codec::iso_8859_7},
    {"elot_928", codec::iso_8859_7},
    {"euc-jp", codec::euc_jp},
    {"euc-kr", codec::euc_kr},
    {"gb18030", codec::gb18030},
    {"gb2312", codec::gbk},
    {"gb_2312", codec::gbk},
    {"gb_2312-80", codec::gbk},
    {"gbk", codec::gbk},
    {"greek", codec::iso_8859_7},
    {"greek8", codec::iso_8859_7},
    {"hebrew", codec::iso_8859_8},
    {"hz-gb-2312", codec::replacement},
    {"ibm819", codec::windows_1252},
    {"ibm866", codec::ibm866},
    {"iso-10646-ucs-2", codec::utf_16le},
    {"iso-2022-cn", codec::replacement},
    {"iso-2022-cn-ext", codec::replacement},
    {"iso-2022-jp", codec::iso_2022_jp},
    {"iso-2022-kr", codec::replacement},
    {"iso-8859-1", codec::windows_1252},
    {"iso-8859-10", codec::iso_8859_10},
    {"iso-8859-11", codec::windows_874},
    {"iso-8859-13", codec::iso_8859_13},
    {"iso-8859-14", codec::iso_8859_14},
    {"iso-8859-15", codec::iso_8859_15},
    {"iso-8859-16", codec::iso_8859_16},
    {"iso-8859-2", codec::iso_8859_2},
    {"iso-8859-3", codec::iso_8859_3},
    {"iso-8859-4", codec::iso_8859_4},
    {"iso-8859-5", codec::iso_8859_5},
    {"iso-8859-6", codec::iso_8859_6},
    {"iso-8859-6-e", codec::iso_8859_6},
    {"iso-8859-6-i", codec::iso_8859_6},
    {"iso-8859-7", codec::iso_8859_7},
    {"iso-8859-8", codec::iso_8859_8},
    {"iso-8859-8-e", codec::iso_8859_8},
    {"iso-8859-8-i", codec::iso_8859_8_i},
    {"iso-8859-9", codec::windows_1254},
    {"iso-ir-100", codec::windows_1252},
    {"iso-ir-101", codec::iso_8859_2},
    {"iso-ir-109", codec::iso_8859_3},
    {"iso-ir-110", codec::iso_8859_4},
    {"iso-ir-126", codec::iso_8859_7},
    {"iso-ir-127", codec::iso_8859_6},
    {"iso-ir-138", codec::iso_8859_8},
    {"iso-ir-144", codec::iso_8859_5},
    {"iso-ir-148", codec::windows_1254},
    {"iso-ir-149", codec::euc_kr},
    {"iso-ir-157", codec::iso_8859_10},
    {"iso-ir-58", codec::gbk},
    {"iso8859-1", codec::windows_1252},
    {"iso8859-10", codec::iso_8859_10},
    {"iso8859-11", codec::windows_874},
    {"iso8859-13", codec::iso_8859_13},
    {"iso8859-14", codec::iso_8859_14},
    {"iso8859-15", codec::iso_8859_15},
    {"iso8859-2", codec::iso_8859_2},
    {"iso8859-3", codec::iso_8859_3},
    {"iso8859-4", codec::iso_8859_4},
    {"iso8859-5", codec::iso_8859_5},
    {"iso8859-6", codec::iso_8859_6},
    {"iso8859-7", codec::iso_8859_7},
    {"iso8859-8", codec::iso_8859_8},
    {"iso8859-9", codec::windows_1254},
    {"iso88591", codec::windows_1252},
    {"iso885910", codec::iso_8859_10},
    {"iso885911", codec::windows_874},
    {"iso885913", codec::iso_8859_13},
    {"iso885914", codec::iso_8859_14},
    {"iso885915", codec::iso_8859_15},
    {"iso88592", codec::iso_8859_2},
    {"iso88593", codec::iso_8859_3},
    {"iso88594", codec::iso_8859_4},
    {"iso88595", codec::iso_8859_5},
    {"iso88596", codec::iso_8859_6},
    {"iso88597", codec::iso_8859_7},
    {"iso88598", codec::iso_8859_8},
    {"iso88599", codec::windows_1254},
    {"iso_8859-1", codec::windows_1252},
    {"iso_8859-15", codec::iso_8859_15},
    {"iso_8859-1:1987", codec::windows_1252},
    {"iso_8859-2", codec::iso_8859_2},
    {"iso_8859-2:1987", codec::iso_8859_2},
    {"iso_8859-3", codec::iso_8859_3},
    {"iso_8859-3:1988", codec::iso_8859_3},
    {"iso_8859-4", codec::iso_8859_4},
    {"iso_8859-4:1988", codec::iso_8859_4},
    {"iso_8859-5", codec::iso_8859_5},
    {"iso_8859-5:1988", codec::iso_8859_5},
    {"iso_8859-6", codec::iso_8859_6},
    {"iso_8859-6:1987", codec::iso_8859_6},
    {"iso_8859-7", codec::iso_8859_7},
    {"iso_8859-7:1987", codec::iso_8859_7},
    {"iso_8859-8", codec::iso_8859_8},
    {"iso_8859-8:1988", codec::iso_8859_8},
    {"iso_8859-9", codec::windows_1254},
    {"iso_8859-9:1989", codec::windows_1254},
    {"koi", codec::koi8_r},
    {"koi8", codec::koi8_r},
    {"koi8-r", codec::koi8_r},
    {"koi8-ru", codec::koi8_u},
    {"koi8-u", codec::koi8_u},
    {"koi8_r", codec::koi8_r},
    {"korean", codec::euc_kr},
    {"ks_c_5601-1987", codec::euc_kr},
    {"ks_c_5601-1989", codec::euc_kr},
    {"ksc5601", codec::euc_kr},
    {"ksc_5601", codec::euc_kr},
    {"l1", codec::windows_1252},
    {"l2", codec::iso_8859_2},
    {"l3", codec::iso_8859_3},
    {"l4", codec::iso_8859_4},
    {"l5", codec::windows_1254},
    {"l6", codec::iso_8859_10},
    {"l9", codec::iso_8859_15},
    {"latin1", codec::windows_1252},
    {"latin2", codec::iso_8859_2},
    {"latin3", codec::iso_8859_3},
    {"latin4", codec::iso_8859_4},
    {"latin5", codec::windows_1254},
    {"latin6", codec::iso_8859_10},
    {"logical", codec::iso_8859_8_i},
    {"mac", codec::macintosh},
    {"macintosh", codec::macintosh},
    {"ms932", codec::shift_jis},
    {"ms_kanji", codec::shift_jis},
    {"replacement", codec::replacement},
    {"shift-jis", codec::shift_jis},
    {"shift_jis", codec::shift_jis},
    {"sjis", codec::shift_jis},
    {"sun_eu_greek", codec::iso_8859_7},
    {"tis-620", codec::windows_874},
    {"ucs-2", codec::utf_16le},
    {"unicode", codec::utf_16le},
    {"unicode-1-1-utf-8", codec::utf_8},
    {"unicode11utf8", codec::utf_8},
    {"unicode20utf8", codec::utf_8},
    {"unicodefeff", codec::utf_16le},
    {"unicodefffe", codec::utf_16be},
    {"us-ascii", codec::windows_1252},
    {"utf-16", codec::utf_16le},
    {"utf-16be", codec::utf_16be},
    {"utf-16le", codec::utf_16le},
    {"utf-8", codec::utf_8},
    {"utf8", codec::utf_8},
    {"visual", codec::iso_8859_8},
    {"windows-1250", codec::windows_1250},
    {"windows-1251", codec::windows_1251},
    {"windows-1252", codec::windows_1252},
    {"windows-1253", codec::windows_1253},
    {"windows-1254", codec::windows_1254},
    {"windows-1255", codec::windows_1255},
    {"windows-1256", codec::windows_1256},
    {"windows-1257", codec::windows_1257},
    {"windows-1258", codec::windows_1258},
    {"windows-31j", codec::shift_jis},
    {"windows-874", codec::windows_874},
    {"windows-949", codec::euc_kr},
    {"x-cp1250", codec::windows_1250},
    {"x-cp1251", codec::windows_1251},
    {"x-cp1252", codec::windows_1252},
    {"x-cp1253", codec::windows_1253},
    {"x-cp1254", codec::windows_1254},
    {"x-cp1255", codec::windows_1255},
    {"x-cp1256", codec::windows_1256},
    {"x-cp1257", codec::windows_1257},
    {"x-cp1258", codec::windows_1258},
    {"x-euc-jp", codec::euc_jp},
    {"x-gbk", codec::gbk},
    {"x-mac-cyrillic", codec::x_mac_cyrillic},
    {"x-mac-roman", codec::macintosh},
    {"x-mac-ukrainian", codec::x_mac_cyrillic},
    {"x-sjis", codec::shift_jis},
    {"x-unicode20utf8", codec::utf_8},
    {"x-user-defined", codec::x_user_defined},
    {"x-x-big5", codec::big5},
};

} // namespace detail

// Returns the canonical codec for a WHATWG label, or nullopt for unknown.
// Case-insensitive; strips leading/trailing ASCII whitespace per WHATWG spec.
constexpr std::optional<codec> get_encoding(std::string_view label) noexcept {
    // Strip ASCII whitespace from both ends (\t \n \f \r \x20).
    auto is_ws = [](char c) noexcept { return c == ' ' || c == '\t' || c == '\n' || c == '\f' || c == '\r'; };
    while (!label.empty() && is_ws(label.front()))
        label.remove_prefix(1);
    while (!label.empty() && is_ws(label.back()))
        label.remove_suffix(1);

    if (label.empty())
        return std::nullopt;

    // ASCII-lowercase the label into a fixed-size buffer (longest label < 64).
    char buf[64];
    if (label.size() >= sizeof(buf))
        return std::nullopt;
    for (std::size_t i = 0; i < label.size(); ++i) {
        char c = label[i];
        buf[i] = (c >= 'A' && c <= 'Z') ? static_cast<char>(c + 32) : c;
    }
    std::string_view lower{buf, label.size()};

    // Binary search the sorted table.
    auto it = std::ranges::lower_bound(
        detail::label_table, lower, {}, [](const detail::label_entry& e) { return std::string_view{e.label}; });
    if (it != std::end(detail::label_table) && std::string_view{it->label} == lower)
        return it->value;
    return std::nullopt;
}

} // namespace beman::transcoding

#endif // INCLUDE_BEMAN_TRANSCODE_DETAIL_LABELS_HPP
