#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
"""Generate include/beman/transcode/detail/labels.hpp from docs/whatwg/encodings.json."""

import json
import re
import subprocess
from pathlib import Path

DOCS_WHATWG = Path("docs/whatwg")
INCLUDE_DETAIL = Path("include/beman/transcode/detail")
CLANG_FORMAT = "clang-format"


def name_to_codec_value(name: str) -> str:
    """Convert WHATWG encoding name to codec enum value identifier."""
    return re.sub(r"[^a-zA-Z0-9]", "_", name).lower()


def parse_encodings_json(path: Path) -> list[tuple[str, str]]:
    """Parse encodings.json; return sorted list of (lowercased_label, codec_value) pairs."""
    data = json.loads(path.read_text(encoding="utf-8"))
    entries: list[tuple[str, str]] = []
    for group in data:
        for enc in group["encodings"]:
            codec_val = name_to_codec_value(enc["name"])
            for label in enc["labels"]:
                entries.append((label.lower(), codec_val))
    entries.sort(key=lambda x: x[0])
    return entries


def render_labels_hpp(entries: list[tuple[str, str]]) -> str:
    """Render the labels.hpp header from sorted (label, codec_value) pairs."""
    table_rows = "\n".join(
        f'    {{"{label}", codec::{codec_val}}},' for label, codec_val in entries
    )
    return f"""\
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
// This file is generated by tools/generate_labels.py — do not edit directly.

#ifndef INCLUDE_BEMAN_TRANSCODE_DETAIL_LABELS_HPP
#define INCLUDE_BEMAN_TRANSCODE_DETAIL_LABELS_HPP

#include <beman/transcode/whatwg_decode_view.hpp>

#include <algorithm>
#include <optional>
#include <string_view>

namespace beman::transcoding {{

namespace detail {{

struct label_entry {{
    const char* label;
    codec       value;
}};

inline constexpr label_entry label_table[] = {{
{table_rows}
}};

}} // namespace detail

// Returns the canonical codec for a WHATWG label, or nullopt for unknown.
// Case-insensitive; strips leading/trailing ASCII whitespace per WHATWG spec.
constexpr std::optional<codec> get_encoding(std::string_view label) noexcept {{
    // Strip ASCII whitespace from both ends (\\t \\n \\f \\r \\x20).
    auto is_ws = [](char c) noexcept {{
        return c == ' ' || c == '\\t' || c == '\\n' || c == '\\f' || c == '\\r';
    }};
    while (!label.empty() && is_ws(label.front())) label.remove_prefix(1);
    while (!label.empty() && is_ws(label.back())) label.remove_suffix(1);

    if (label.empty()) return std::nullopt;

    // ASCII-lowercase the label into a fixed-size buffer (longest label < 64).
    char buf[64];
    if (label.size() >= sizeof(buf)) return std::nullopt;
    for (std::size_t i = 0; i < label.size(); ++i) {{
        char c = label[i];
        buf[i] = (c >= 'A' && c <= 'Z') ? static_cast<char>(c + 32) : c;
    }}
    std::string_view lower{{buf, label.size()}};

    // Binary search the sorted table.
    auto it = std::ranges::lower_bound(
        detail::label_table,
        lower,
        {{}},
        [](const detail::label_entry& e) {{ return std::string_view{{e.label}}; }});
    if (it != std::end(detail::label_table) && std::string_view{{it->label}} == lower)
        return it->value;
    return std::nullopt;
}}

}} // namespace beman::transcoding

#endif // INCLUDE_BEMAN_TRANSCODE_DETAIL_LABELS_HPP
"""


def main() -> None:
    encodings_path = DOCS_WHATWG / "encodings.json"
    output_path = INCLUDE_DETAIL / "labels.hpp"

    entries = parse_encodings_json(encodings_path)
    content = render_labels_hpp(entries)

    output_path.write_text(content, encoding="utf-8")

    try:
        subprocess.run([CLANG_FORMAT, "-i", str(output_path)], check=True)
    except FileNotFoundError:
        pass


if __name__ == "__main__":
    main()
