#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
"""Generate detail/labels.hpp from docs/whatwg/encodings.json."""

import contextlib
import json
import re
import subprocess
from pathlib import Path

DOCS_WHATWG = Path("docs/whatwg")
INCLUDE_DETAIL = Path("include/beman/transcode/detail")
CLANG_FORMAT = "clang-format"


def name_to_codec_value(name: str) -> str:
    """Convert WHATWG encoding name to codec enum value identifier."""
    return re.sub(r"[^a-zA-Z0-9]", "_", name).lower()


def parse_encodings_json(path: Path) -> list[tuple[str, str]]:
    """Parse encodings.json.

    Return sorted list of (lowercased_label, codec_value) pairs.
    """
    data = json.loads(path.read_text(encoding="utf-8"))
    entries: list[tuple[str, str]] = []
    for group in data:
        for enc in group["encodings"]:
            codec_val = name_to_codec_value(enc["name"])
            for label in enc["labels"]:
                entries.append((label.lower(), codec_val))
    entries.sort(key=lambda x: x[0])
    return entries


def render_labels_hpp(entries: list[tuple[str, str]]) -> str:
    """Render the labels.hpp header from sorted (label, codec_value) pairs."""
    table_rows = "\n".join(
        f'    {{"{label}", codec::{codec_val}}},' for label, codec_val in entries
    )
    return f"""\
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
// This file is generated by tools/generate_labels.py — do not edit directly.

#ifndef INCLUDE_BEMAN_TRANSCODE_DETAIL_LABELS_HPP
#define INCLUDE_BEMAN_TRANSCODE_DETAIL_LABELS_HPP

#include <beman/transcode/codec.hpp>

namespace beman::transcoding::detail {{

struct label_entry {{
    const char* label;
    codec       value;
}};

inline constexpr label_entry label_table[] = {{
{table_rows}
}};

}} // namespace beman::transcoding::detail

#endif // INCLUDE_BEMAN_TRANSCODE_DETAIL_LABELS_HPP
"""


def main() -> None:
    encodings_path = DOCS_WHATWG / "encodings.json"
    output_path = INCLUDE_DETAIL / "labels.hpp"

    entries = parse_encodings_json(encodings_path)
    content = render_labels_hpp(entries)

    output_path.write_text(content, encoding="utf-8")

    with contextlib.suppress(FileNotFoundError):
        subprocess.run([CLANG_FORMAT, "-i", str(output_path)], check=True)


if __name__ == "__main__":
    main()
